#!/usr/bin/env python3

from simple_term_menu import TerminalMenu
import sys
import curses
import os
import zipfile
import subprocess
from pathlib import Path

def openZipFile(zip_file_path, callback):
    try:
        # Open the zip file
        with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
            callback(zip_ref)

    except FileNotFoundError:
        print("File not found:", zip_file_path)
    except zipfile.BadZipFile:
        print("Invalid zip file:", zip_file_path)



gnome_desktops = ['X-Cinnamon', 'XFCE']


def is_gnome(desktop):
    if desktop.endswith("GNOME") or desktop in gnome_desktops:
        return True
    return False


def target():
    current_desktop = os.environ['XDG_CURRENT_DESKTOP']
    if is_gnome(current_desktop):
        return 'x-special/gnome-copied-files'
    else:
        return 'text/uri-list'

def base_copy_cmd():
    if 'WAYLAND_DISPLAY' in os.environ:
        return 'wl-copy'
    return 'xclip -i -selection clipboard'


def copy_clipboard_cmd():
    return f"{base_copy_cmd()} -t '{target()}'"


def content(files_to_copy):
    uris = '\n'.join([Path(f).as_uri() for f in files_to_copy])
    current_desktop = os.environ['XDG_CURRENT_DESKTOP']
    if is_gnome(current_desktop):
        return f"copy\n{uris}".encode("utf-8")
    return uris.encode("utf-8")


def copy_to_clipboard(files_to_copy):
    copy_process = subprocess.Popen(copy_clipboard_cmd(), shell=True, stdin=subprocess.PIPE)
    copy_process.stdin.write(content(files_to_copy))
    copy_process.stdin.close()
    copy_process.wait()

def main(zip_ref):
    zip_content = []

    for file_info in zip_ref.infolist():
        if file_info.is_dir():
            # print("Folder:", file_info.filename)
            pass
        else:
            zip_content.append( file_info.filename )

    terminal_menu = TerminalMenu(
        zip_content,
        multi_select=True,
        show_multi_select_hint=False,
    )

    menu_entry_indices = terminal_menu.show()

    file_list = [] 
    for name in terminal_menu.chosen_menu_entries:
        zip_ref.extract(name, "/tmp")
        extracted_file_path = os.path.join('/tmp', name)
        file_list.append(extracted_file_path)

    copy_to_clipboard(file_list)
    input("wait")

zipPath = sys.argv[1]
openZipFile(zipPath, main)


